### ISSUE TITLE
Minor POD problems

### ISSUE THREAD

**Issue by gsullivan** [benkasminbullock/Directory-Diff#1]
There is a typo in the SYNOPSIS of the Diff.pm POD.  This:

{diff => &diff

should be:

{diff => &diff,

Also, these links in the POD do not work on metacpan ("Not Found" error):

`L<directory_diff>`
`L<ls_dir>`

I don't know how to fix those

**Comment by benkasminbullock** [comment]
Thank you for reporting these problems. I have altered the code to correct them.

You can see the commit here: d39b2177b90ec52290598389fbc19ac5c5416825.

`L</directory_diff>` with a `\` after `<` is required.

This is in release 0.02, currently released to CPAN.

Thanks again.
